spring.application.name=storage-service

server.port=8082

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

#dfs.storage.dir=../dfs-java-project/storage

# application.properties (example for multiple nodes)

# Node 1
#server.port=8082
#storage.path=storage1

# Node 2 (run separately)
# server.port=8083
# storage.path=storage2

# Node 3 (run separately)
# server.port=8084
# storage.path=storage3
